// src/config.ts
// All external "addresses" and tunable knobs live here so they can change without a
// code hunt. If an upstream URL ever moves, edit it here (or expose it in Advanced
// settings) — no need to touch the rest of the app.
//
// NOTE: replace ericjrtan/lubs-cart-ffxiv once the GitHub repo exists. If you enable GitHub
// Pages for the repo, you can swap the raw.githubusercontent.com URLs for the Pages URL
// (https://YOURUSER.github.io/YOURREPO/items.json) for a cleaner CDN.

export const config = {
  // --- Universalis (market board data) ---
  universalisBase: 'https://universalis.app/api/v2',

  // --- XIVAPI (item icons, fetched lazily then cached to disk) ---
  // Use v2: the old v1 (xivapi.com) is frozen and 404s newer items' icons; v2 has them all
  // (verified June 2026) and sends CORS *. URL shape: /api/asset?path=ui/icon/<f>/<file>.tex&format=png
  xivapiIconBase: 'https://v2.xivapi.com',

  // --- FFXIV Wiki (right-click "View on wiki") ---
  wikiBase: 'https://ffxiv.consolegameswiki.com',
  wikiSearchPath: '/index.php?search=', // fallback when a page name doesn't resolve 1:1
  // Verified June 2026: the MediaWiki API lives under /mediawiki/ (not /api.php), and
  // returns Access-Control-Allow-Origin: * so the existence check works from the webview.
  wikiApiPath: '/mediawiki/api.php',

  // --- Hosted data (live layer of the live -> cached -> bundled fallback) ---
  itemsRemoteUrl:  'https://raw.githubusercontent.com/ericjrtan/lubs-cart-ffxiv/main/public/items.json.gz',
  statusRemoteUrl: 'https://raw.githubusercontent.com/ericjrtan/lubs-cart-ffxiv/main/public/status.json',

  // --- Currency exchange data (Currency tab) — live -> cached -> bundled, like items.json.
  // Auto-generated by scripts/build-currencies.mjs; <base>index.json lists the currencies,
  // <base><id>.json holds one currency's flippable items. Bundled copies live in public/.
  currenciesUrlBase: 'https://raw.githubusercontent.com/ericjrtan/lubs-cart-ffxiv/main/public/currencies/',
  currenciesBundledBase: '/currencies/', // shipped inside the app (vite copies public/ to root)

  // --- Where friends download new versions (used by the status.json update banner) ---
  releasesUrl: 'https://github.com/ericjrtan/lubs-cart-ffxiv/releases/latest',

  // --- Networking behaviour ---
  requestTimeoutMs: 8000,    // per request; keep short so a slow network never hangs startup
  maxConcurrency: 4,         // simultaneous in-flight requests (be polite to Universalis)
  itemIdsPerRequest: 100,    // chunk size for multi-item queries (verified: 100 works live)
  listingsPerItem: 100,      // listings=N cap per item, generous so big quantities can fill
  requestDelayMs: 150,       // small gap between request starts (be polite to Cloudflare)
  maxRetries: 3,             // retries on 429 / 503 / network error (exponential backoff)
  iconBatchSize: 6,          // icons fetched in parallel per batch

  // --- Selling (Currency/Crafting tabs) ---
  // In current FFXIV the BUYER pays the market tax on top; the seller receives the full listed
  // price. So sell revenue = price (no deduction) and this stays 0. Kept as a knob in case the
  // model changes. (Buying still includes per-listing tax — handled in cheapest.ts.)
  sellTaxRate: 0,
  // Listings at/above this are treated as troll/placeholder prices (sellers park items ~1 gil
  // under the 999,999,999 cap) and ignored, falling back to the recent average sale price.
  junkPriceThreshold: 100_000_000,
  // Default "hide rarely sold" cutoff for the Currency flip table (sales/day); a flip you
  // can't actually sell isn't a flip. Users can toggle the filter off.
  lowVelocityThreshold: 1,
  // Budget optimizer: how many days of sales you're willing to wait to clear an item. Each
  // item's realistic sellable quantity = sales/day × this, so the plan won't tell you to buy
  // 1,700 of something that only sells ~24/day. ~1 week is a sensible default.
  budgetSellHorizonDays: 7,

  // --- Freshness ---
  staleDataThresholdMs: 1000 * 60 * 60 * 6, // warn if a DC's last upload is older than 6h

  // --- Data centers to hide (by region) ---
  // "NA Cloud DC (Beta)" is a separate beta region with no real shopping value; drop it.
  hiddenDcRegions: ['NA-Cloud-DC'] as readonly string[],

  // --- App version (compare against status.json.latestVersion to show "update available") ---
  appVersion: '1.0.1',
} as const;

export type AppConfig = typeof config;
